<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_id
 * @property string $first_name
 * @property string $last_name
 * @property string $phone
 * @property string $movil
 * @property string $email
 * @property string $address
 * @property string $position
 * @property Client $Client
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getClientId()   Returns the current record's "client_id" value
 * @method string  getFirstName()  Returns the current record's "first_name" value
 * @method string  getLastName()   Returns the current record's "last_name" value
 * @method string  getPhone()      Returns the current record's "phone" value
 * @method string  getMovil()      Returns the current record's "movil" value
 * @method string  getEmail()      Returns the current record's "email" value
 * @method string  getAddress()    Returns the current record's "address" value
 * @method string  getPosition()   Returns the current record's "position" value
 * @method Client  getClient()     Returns the current record's "Client" value
 * @method Contact setId()         Sets the current record's "id" value
 * @method Contact setClientId()   Sets the current record's "client_id" value
 * @method Contact setFirstName()  Sets the current record's "first_name" value
 * @method Contact setLastName()   Sets the current record's "last_name" value
 * @method Contact setPhone()      Sets the current record's "phone" value
 * @method Contact setMovil()      Sets the current record's "movil" value
 * @method Contact setEmail()      Sets the current record's "email" value
 * @method Contact setAddress()    Sets the current record's "address" value
 * @method Contact setPosition()   Sets the current record's "position" value
 * @method Contact setClient()     Sets the current record's "Client" value
 * 
 * @package    limbo
 * @subpackage model
 * @author     Damian Suarez / Laura Melo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('first_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('last_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('phone', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('movil', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('email', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('address', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('position', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}