<?php

/**
 * BaseClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property string $phone
 * @property string $cuit
 * @property string $logo
 * @property Doctrine_Collection $Contacts
 * @property Doctrine_Collection $Proposals
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getAddress()   Returns the current record's "address" value
 * @method string              getPhone()     Returns the current record's "phone" value
 * @method string              getCuit()      Returns the current record's "cuit" value
 * @method string              getLogo()      Returns the current record's "logo" value
 * @method Doctrine_Collection getContacts()  Returns the current record's "Contacts" collection
 * @method Doctrine_Collection getProposals() Returns the current record's "Proposals" collection
 * @method Client              setId()        Sets the current record's "id" value
 * @method Client              setName()      Sets the current record's "name" value
 * @method Client              setAddress()   Sets the current record's "address" value
 * @method Client              setPhone()     Sets the current record's "phone" value
 * @method Client              setCuit()      Sets the current record's "cuit" value
 * @method Client              setLogo()      Sets the current record's "logo" value
 * @method Client              setContacts()  Sets the current record's "Contacts" collection
 * @method Client              setProposals() Sets the current record's "Proposals" collection
 * 
 * @package    limbo
 * @subpackage model
 * @author     Damian Suarez / Laura Melo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('address', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('phone', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('cuit', 'string', 13, array(
             'type' => 'string',
             'length' => 13,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClientContact as Contacts', array(
             'local' => 'id',
             'foreign' => 'client_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Proposal as Proposals', array(
             'local' => 'id',
             'foreign' => 'client_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}