<?php

/**
 * BaseServiceItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $service_id
 * @property integer $item_id
 * 
 * @method integer     getServiceId()  Returns the current record's "service_id" value
 * @method integer     getItemId()     Returns the current record's "item_id" value
 * @method ServiceItem setServiceId()  Sets the current record's "service_id" value
 * @method ServiceItem setItemId()     Sets the current record's "item_id" value
 * 
 * @package    limbo
 * @subpackage model
 * @author     Damian Suarez / Laura Melo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiceItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service_item');
        $this->hasColumn('service_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}