generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Proposal
    theme:                 mooDoo.2
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          proposal
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      list:
        display:                [ number, date, client, description]
        actions:
          _new:                 { label: '&nbsp;', atts: {title: Add page } }
        batch_actions:
          delete:
        fields:
          date:                 { date_format :'dd-MM-yyyy' }
        object_actions:
          _edit:                ~
          _delete:              ~
          print:                { label: 'Print report' }

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
